services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    umanit_block_collection.form.type_extension.ckeditor:
        class: Umanit\BlockCollectionBundle\Form\Extension\CKEditorTypeExtension
        arguments: ['@fos_ck_editor.configuration', '@fos_ck_editor.renderer']
        tags: ['form.type_extension']

    umanit_block_collection.block_manager.faq:
        class: Umanit\BlockCollectionBundle\BlockManager\FaqBlockManager
        arguments: ['@twig']
        tags: ['umanit_block.manager']

    umanit_block_collection.block_manager.image:
        class: Umanit\BlockCollectionBundle\BlockManager\ImageBlockManager
        arguments: ['@twig']
        tags: ['umanit_block.manager']

    umanit_block_collection.block_manager.images_list:
        class: Umanit\BlockCollectionBundle\BlockManager\ImagesListBlockManager
        arguments: ['@twig']
        tags: ['umanit_block.manager']

    umanit_block_collection.block_manager.link:
        class: Umanit\BlockCollectionBundle\BlockManager\LinkBlockManager
        arguments: ['@twig']
        tags: ['umanit_block.manager']

    umanit_block_collection.block_manager.quote:
        class: Umanit\BlockCollectionBundle\BlockManager\QuoteBlockManager
        arguments: ['@twig']
        tags: ['umanit_block.manager']

    umanit_block_collection.block_manager.triptych:
        class: Umanit\BlockCollectionBundle\BlockManager\TriptychBlockManager
        arguments: ['@twig']
        tags: ['umanit_block.manager']

    umanit_block_collection.block_manager.video:
        class: Umanit\BlockCollectionBundle\BlockManager\VideoBlockManager
        arguments: ['@twig']
        tags: ['umanit_block.manager']

    umanit_block_collection.block_manager.wysiwyg:
        class: Umanit\BlockCollectionBundle\BlockManager\WysiwygBlockManager
        arguments: ['@twig']
        tags: ['umanit_block.manager']

    umanit_block_collection.video_detector.vimeo:
        class: Umanit\BlockCollectionBundle\VideoDetector\Vimeo
        tags: ['umanit_block_collection.video_detector']

    umanit_block_collection.video_detector.youtube:
        class: Umanit\BlockCollectionBundle\VideoDetector\YouTube
        tags: ['umanit_block_collection.video_detector']

    umanit_block_collection.video_detector.youku:
        class: Umanit\BlockCollectionBundle\VideoDetector\Youku
        tags: ['umanit_block_collection.video_detector']

    umanit_block_collection.validator.embeddable_video:
        class: Umanit\BlockCollectionBundle\Validator\Constraints\EmbeddableVideoValidator
        arguments: [!tagged_iterator umanit_block_collection.video_detector]
        tags: ['validator.constraint_validator']

    umanit_block_collection.twig_extension:
        class: Umanit\BlockCollectionBundle\Twig\BlockCollectionExtension
        tags: ['twig.extension']

    umanit_block_collection.twig_runtime:
        class: Umanit\BlockCollectionBundle\Twig\BlockCollectionRuntime
        arguments: [!tagged_iterator umanit_block_collection.video_detector]
        tags: ['twig.runtime']
